// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hnl.veiculos.com.br.Data;

namespace hnl.veiculos.com.br.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("hnl.veiculos.com.br.Entities.Marca", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IMAGEM")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NOME");

                    b.HasKey("ID");

                    b.ToTable("Marca");
                });

            modelBuilder.Entity("hnl.veiculos.com.br.Entities.Modelo", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IDMARCA");

                    b.Property<string>("IMAGEM");

                    b.Property<string>("MARCA");

                    b.Property<Guid?>("MarcaID");

                    b.Property<string>("NOME")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("ID");

                    b.HasIndex("MarcaID");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("hnl.veiculos.com.br.Entities.Modelo", b =>
                {
                    b.HasOne("hnl.veiculos.com.br.Entities.Marca")
                        .WithMany("MODELOS")
                        .HasForeignKey("MarcaID");
                });
#pragma warning restore 612, 618
        }
    }
}
